socraticorg/mathsteps

- lib/simplifyExpression.js
- lib/solveEquation.js
I think in general, the step should match the nodeStatus as much as possible
> explanation -> changeType

- lib/simplifyExpression.js
- lib/solveEquation.js
- test/simplifyExpression.test.js
this was more headache than it's worth
from now on, we'll just always print + - as - and not support the + - => - step
some solvers wouldn't even support two operators side by side like that, so I think this is the better choice for the solver
> no plus minus step

- lib/ConstantFraction.js
- lib/Equation.js
- lib/EquationOperations.js
- lib/EquationStatus.js
- lib/MathChangeTypes.js
- lib/NodeStatus.js
- lib/PolynomialTermOperations.js
- lib/collectAndCombine.js
- lib/evaluateConstantSum.js
- lib/simplifyExpression.js
- lib/solveEquation.js
- test/Fraction.test.js
- test/PolynomialTerm.test.js
- test/collectAndCombine.test.js
- test/evaluateConstantSum.test.js
- test/solveEquation.test.js
> equation substeps and changegroups

- lib/Factor.js
- lib/MathChangeTypes.js
- lib/Negative.js
- lib/NodeCreator.js
- lib/evaluateFunctions.js
- lib/flattenOperands.js
- lib/hasUnsupportedNodes.js
- test/NodeType.test.js
- test/evaluateFunctions.test.js
- test/simplifyExpression.test.js
This code ended up being a mess...
[asana task](https://app.asana.com/0/201972293666219/198715212854040)
> adding root support functionality

- lib/distribute.js
This removes a bunch of cloning from distribute. Unfortunately, it doesn't make distribute that much faster in these cases. I originally thought it did, but I realized my test was wrong.
> Small distribution cleanup attempt

- lib/PolynomialTermOperations.js
- test/PolynomialTerm.test.js
- test/solveEquation.test.js
[asana](https://app.asana.com/0/201972293666219/228523808431555) [tasks](https://app.asana.com/0/201972293666219/226870543316280)
> divide decimal fraction coefficients

- lib/solveEquation.js
- test/solveEquation.test.js
[asana task](https://app.asana.com/0/201972293666219/228523808431564)
and added the fix to https://sentry.io/socratic/athena/issues/193077935/ because it was also an equations thing
> fix Expected both nodes to be constants error

- index.js
- lib/checks/index.js
- lib/equation/index.js
- lib/node/index.js
Changed to use property shorthand notation to make shorter and more readable. This should address issue #80
> use property value shorthand

- lib/Symbols.js
- lib/node/Type.js
- lib/simplifyExpression/collectAndCombineSearch/LikeTermCollector.js
- lib/simplifyExpression/distributeSearch/index.js
- lib/simplifyExpression/fractionsSearch/cancelLikeTerms.js
- lib/simplifyExpression/functionsSearch/nthRoot.js
- lib/simplifyExpression/multiplyFractionsSearch/index.js
- test/Node/Type.test.js
addresses #31 
Added parameter to accept a String operator into isOperator (defaulted to null). Refactored isOperator usage throughout app where applicable. Adequate tests added as well.
> Refactor isOperator to accept operator parameter

- RESOURCES.md
Create a section for open source software that is related to step-by-step
equation solving which may be useful for mathsteps.
> Add information on PRESS, MathPiper, and MathCraft.

- .travis.yml
> add linter to travis

- lib/factor/factorQuadratic.js
- lib/node/PolynomialTerm.js
- lib/simplifyExpression/arithmeticSearch/index.js
- lib/simplifyExpression/fractionsSearch/addConstantAndFraction.js
- lib/simplifyExpression/fractionsSearch/addConstantFractions.js
- lib/simplifyExpression/fractionsSearch/divideByGCD.js
- lib/simplifyExpression/functionsSearch/absoluteValue.js
- lib/solveEquation/stepThrough.js
- lib/util/evaluate.js
- lib/util/flattenOperands.js
> replace eval() with evaluate()

- lib/checks/canMultiplyLikeTermConstantNodes.js
https://github.com/socraticorg/mathsteps/commit/1083124f163a196d0686677a63a264df41ea5b84#commitcomment-22937523
> fixes bug #153

- lib/checks/canMultiplyLikeTermConstantNodes.js
- test/simplifyExpression/arithmeticSearch/arithmeticSearch.test.js
- test/simplifyExpression/oneStep.test.js
https://github.com/socraticorg/mathsteps/pull/180#discussion_r125961158
> better fix for multiplying like term constant nodes

- lib/simplifyExpression/fractionsSearch/cancelLikeTerms.js
- test/simplifyExpression/fractionsSearch/cancelLikeTerms.test.js
- test/simplifyExpression/simplify.test.js
> Add two more cases for cancelling terms

- lib/ChangeTypes.js
- lib/simplifyExpression/fractionsSearch/divideByGCD.js
- test/simplifyExpression/fractionsSearch/divideByGCD.test.js
https://github.com/socraticorg/mathsteps/issues/41
> greatest common denominator substep

- lib/simplifyExpression/arithmeticSearch/index.js
- test/simplifyExpression/arithmeticSearch/arithmeticSearch.test.js
- test/solveEquation/solveEquation.test.js
Fixed bug #162, and added tests to check that large negative
numbers do not round.  Also commented out broken test related to
test #162.
> #162 bugfix - Large negtive number rounding

- .eslintrc.js
- lib/TreeSearch.js
- package-lock.json
> Issue #220 - Added linting rules

- lib/simplifyExpression/functionsSearch/nthRoot.js
- test/simplifyExpression/functionsSearch/nthRoot.test.js
> Fix the check for perfect roots of a constant when there's roundoff error.

- lib/simplifyExpression/fractionsSearch/cancelLikeTerms.js
- test/simplifyExpression/fractionsSearch/cancelLikeTerms.test.js
- test/simplifyExpression/simplify.test.js
> Expressions with polynomials divided by polynomials are now simplified
